const API = 'https://script.google.com/macros/s/AKfycbxKIjfB_RJZBteGtUVZhQJmFmIwCzPAmF1CyZNGZPakhoFJaPYu5M7uUuUjRKl4g7KM/exec', STORE = 'abhyasikha-supervision-v5', SESSION_LIMIT_MS = 3 * 60 * 60 * 1000;
let mode = 'LIVE', recordId = '', geo = null, photo = null, outGeo = null, outPhoto = null, previousPhotos = { pin: null, pout: null }, cameraStream = null, cameraTarget = null, checkInTime = null, expiryTimer = null;
const $ = id => document.getElementById(id);
function svgCheck() { return '<svg class="icon" viewBox="0 0 24 24"><path d="m6 12 4 4 8-8"/></svg>' }
function today() { const d = new Date(); return d.getFullYear() + '-' + String(d.getMonth() + 1).padStart(2, '0') + '-' + String(d.getDate()).padStart(2, '0') }
function yesterday() { const d = new Date(); d.setDate(d.getDate() - 1); return d.toISOString().slice(0, 10) }
function show(id) { document.querySelectorAll('.screen').forEach(x => x.classList.remove('active')); $(id).classList.add('active'); scrollTo(0, 0) }
function toast(s) { $('toast').textContent = s; $('toast').style.display = 'block'; clearTimeout(window._toast); window._toast = setTimeout(() => $('toast').style.display = 'none', 4200) }
function setTheme(t) { document.documentElement.dataset.theme = t; localStorage.setItem('as-theme', t); $('themeBtn').innerHTML = t === 'dark' ? '<svg class="icon" viewBox="0 0 24 24"><path d="M12 3v2M12 19v2M3 12h2M19 12h2M5.6 5.6l1.4 1.4M17 17l1.4 1.4M18.4 5.6 17 7M7 17l-1.4 1.4"/><circle cx="12" cy="12" r="4"/></svg>' : '<svg class="icon" viewBox="0 0 24 24"><path d="M21 12.8A8.5 8.5 0 1 1 11.2 3 6.8 6.8 0 0 0 21 12.8Z"/></svg>'; document.querySelector('meta[name="theme-color"]').content = getComputedStyle(document.documentElement).getPropertyValue('--background').trim() || '#fff' }
function toggleTheme() { setTheme(document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark') }
function normalizeName(v, trim = false) { const normalized = String(v || '').replace(/[^A-Za-z., ]/g, '').replace(/ +/g, ' ').replace(/^ +/, ''); const value = trim ? normalized.trim() : normalized; return value.replace(/\b([A-Za-z])([A-Za-z]*)\b/g, (_, a, r) => a.toUpperCase() + r.toLowerCase()) }
function normalizeSchool(v, trim = false) { const normalized = String(v || '').replace(/[^A-Za-z., ]/g, '').replace(/ +/g, ' ').replace(/^ +/, ''); return (trim ? normalized.trim() : normalized).replace(/\b([A-Za-z])([A-Za-z]*)\b/g, (_, a, r) => a.toUpperCase() + r.toLowerCase()) }
function setDateMode() { if (mode === 'LIVE') { $('date').value = today(); $('date').disabled = true; $('date').min = today(); $('date').max = today(); $('dateHint').textContent = 'Live supervision date is automatically today.' } else { $('date').value = ''; $('date').disabled = false; $('date').min = '2000-01-01'; $('date').max = yesterday(); $('dateHint').textContent = 'Previous supervision must be before today. Today and future dates are blocked.' } }
function clearSession() { localStorage.removeItem(STORE); clearTimeout(expiryTimer); expiryTimer = null; recordId = ''; geo = null; photo = null; outGeo = null; outPhoto = null; checkInTime = null; previousPhotos = { pin: null, pout: null } }
function saveActive() { localStorage.setItem(STORE, JSON.stringify({ mode, recordId, geo, photo, outGeo, outPhoto, checkInTime, form: { visitor: $('visitor').value, school: $('school').value, date: $('date').value, open: $('open').value, close: $('close').value, notes: $('notes').value } })) }
function loadActive() { try { return JSON.parse(localStorage.getItem(STORE) || 'null') } catch (e) { return null } }
function scheduleExpiry() { clearTimeout(expiryTimer); if (!checkInTime) return; const remaining = SESSION_LIMIT_MS - (Date.now() - new Date(checkInTime).getTime()); if (remaining <= 0) { expireActiveSession(); return } expiryTimer = setTimeout(expireActiveSession, remaining) }
async function expireActiveSession() { if (!recordId) return; const expiredId = recordId; send('expireSession', { recordId: expiredId }).catch(() => {}); clearSession(); show('home'); toast('The session expired after 3 hours without check-out.') }
function init() { setTheme(localStorage.getItem('as-theme') || 'light'); setDateMode(); $('close').disabled = true; $('visitor').addEventListener('input', e => e.target.value = normalizeName(e.target.value)); $('school').addEventListener('input', e => e.target.value = normalizeSchool(e.target.value)); $('open').addEventListener('input', openingChanged); $('close').addEventListener('input', closingChanged); const a = loadActive(); if (a && a.recordId) { restoreActive(a) } }
function start(m) { clearSession(); mode = m; setDateMode(); $('visitor').value = ''; $('school').value = ''; $('open').value = ''; $('close').value = ''; $('notes').value = ''; $('close').disabled = true; show('details') }
function newSession() { clearSession(); location.reload() }
function openingChanged() { const v = $('open').value; $('close').disabled = !v; if (!v) $('close').value = ''; closingChanged() }
function mins(t) { const a = String(t || '').split(':').map(Number); return a[0] * 60 + a[1] }
function closingChanged() { const o = $('open').value, c = $('close').value; let m = ''; if (c && o) { if (mins(c) <= mins(o)) m = 'Closing time must be later than opening time.'; else if (mins(c) - mins(o) <= 120) m = 'Closing time must be more than 2 hours after opening time.' } $('closeErr').textContent = m }
function validDetails() { let ok = true; const v = normalizeName($('visitor').value, true), s = normalizeSchool($('school').value, true); $('visitor').value = v; $('school').value = s; $('visitorErr').textContent = /^(?=.*[A-Za-z])[A-Za-z.,]+(?: [A-Za-z.,]+)*$/.test(v) && v.length >= 2 && v.length <= 80 ? '' : 'Enter a valid 2–80 character supervisor name.'; $('schoolErr').textContent = /^(?=.*[A-Za-z])[A-Za-z.,]+(?: [A-Za-z.,]+)*$/.test(s) && s.length >= 2 && s.length <= 150 ? '' : 'Enter a valid 2–150 character school name.'; $('dateErr').textContent = $('date').value ? '' : 'Visit date is required.'; $('openErr').textContent = $('open').value ? '' : 'Opening time is required.'; closingChanged(); if (!$('close').value) $('closeErr').textContent = 'Closing time is required.'; if (mode === 'LIVE' && $('date').value !== today()) $('dateErr').textContent = 'Live supervision date must be today.'; if (mode === 'PREVIOUS' && $('date').value >= today()) $('dateErr').textContent = 'Previous supervision date must be before today.'; document.querySelectorAll('#details .error').forEach(e => { if (e.textContent) ok = false }); return ok }
function details() { return { recordId, visitType: mode, visitorName: normalizeName($('visitor').value, true), schoolName: normalizeSchool($('school').value, true), visitDate: $('date').value, schoolOpeningTime: $('open').value, schoolClosingTime: $('close').value, notes: $('notes').value, userAgent: navigator.userAgent } }
function send(action, data) { return fetch(API, { method: 'POST', mode: 'no-cors', headers: { 'Content-Type': 'text/plain;charset=UTF-8' }, body: JSON.stringify({ action, data }) }) }
function continueDetails() { if (!validDetails()) return; if (mode === 'LIVE') { show('checkin'); getLocation() } else { show('previous'); } }
function locationUi(ok, failed, meta, text, icon) { $(icon).classList.toggle('ok', ok); $(icon).classList.toggle('bad', failed); $(text).className = 'statusline ' + (ok ? 'status ok' : failed ? 'status bad' : ''); }
function getLocation() { if (!window.isSecureContext) { setLocationError('Location requires HTTPS. Open this page from an HTTPS web app.'); return } if (!navigator.geolocation) { setLocationError('This device/browser does not support location.'); return } $('locText').textContent = 'Requesting location permission…'; $('locText').className = 'statusline'; $('locIcon').classList.remove('ok', 'bad'); navigator.geolocation.getCurrentPosition(p => { if (p.coords.accuracy > 500) { setLocationError('Location accuracy is too low: ±' + Math.round(p.coords.accuracy) + ' m. Improve GPS and try again.'); return } geo = { latitude: p.coords.latitude, longitude: p.coords.longitude, accuracy: p.coords.accuracy }; $('locIcon').classList.add('ok'); $('locText').innerHTML = svgCheck() + ' Location successfully fetched'; $('locText').className = 'statusline status ok'; $('locMeta').textContent = 'Latitude ' + geo.latitude.toFixed(6) + ' · Longitude ' + geo.longitude.toFixed(6) + ' · Accuracy ±' + Math.round(geo.accuracy) + ' m'; $('cameraBtn').disabled = false; $('cameraText').textContent = 'Location verified. Open the camera to continue.'; toast('Location fetched successfully.') }, e => { setLocationError(e.code === 1 ? 'Location permission denied. Enable location permission for this website.' : e.code === 2 ? 'Location unavailable. Turn on phone GPS/location.' : 'Location timed out. Try again in an open area.') }, { enableHighAccuracy: true, timeout: 20000, maximumAge: 0 }) }
function setLocationError(m) { geo = null; $('locIcon').classList.remove('ok'); $('locIcon').classList.add('bad'); $('locText').textContent = '✕ ' + m; $('locText').className = 'statusline status bad'; $('locMeta').textContent = ''; $('cameraBtn').disabled = true; $('checkinBtn').disabled = true; $('cameraText').textContent = 'Camera is blocked until valid location is available.'; $('cameraText').className = 'statusline status bad' }
function getCheckoutLocation() { if (!window.isSecureContext) { setOutLocError('Location requires HTTPS. Open this page from an HTTPS web app.'); return } if (!navigator.geolocation) { setOutLocError('This device/browser does not support location.'); return } $('outLocText').textContent = 'Requesting location permission…'; $('outLocText').className = 'statusline'; $('outLocIcon').classList.remove('ok', 'bad'); navigator.geolocation.getCurrentPosition(p => { if (p.coords.accuracy > 500) { setOutLocError('Location accuracy is too low: ±' + Math.round(p.coords.accuracy) + ' m.'); return } outGeo = { latitude: p.coords.latitude, longitude: p.coords.longitude, accuracy: p.coords.accuracy }; $('outLocIcon').classList.add('ok'); $('outLocText').innerHTML = svgCheck() + ' Location successfully fetched'; $('outLocText').className = 'statusline status ok'; $('outLocMeta').textContent = 'Latitude ' + outGeo.latitude.toFixed(6) + ' · Longitude ' + outGeo.longitude.toFixed(6) + ' · Accuracy ±' + Math.round(outGeo.accuracy) + ' m'; $('outCameraBtn').disabled = false }, e => setOutLocError(e.code === 1 ? 'Location permission denied. Enable permission.' : e.code === 2 ? 'Location unavailable. Turn on GPS/location.' : 'Location timed out. Try again.'), { enableHighAccuracy: true, timeout: 20000, maximumAge: 0 }) }
function setOutLocError(m) { outGeo = null; $('outLocIcon').classList.remove('ok'); $('outLocIcon').classList.add('bad'); $('outLocText').textContent = '✕ ' + m; $('outLocText').className = 'statusline status bad'; $('outCameraBtn').disabled = true; $('checkoutBtn').disabled = true; $('outCameraText').textContent = 'Camera is blocked until valid location is available.'; $('outCameraText').className = 'statusline status bad' }
async function openLiveCamera() { cameraTarget = 'checkin'; if (!geo) { cameraError('Fetch a valid location before opening the camera.'); return } if (!window.isSecureContext) { cameraError('Camera requires HTTPS. Open this page from an HTTPS web app.'); return } if (!navigator.mediaDevices?.getUserMedia) { cameraError('Camera is not supported on this device/browser. Photo upload is disabled.'); return } await openCamera() }
async function openCheckoutCamera() { cameraTarget = 'checkout'; if (!outGeo) { cameraError('Fetch a valid checkout location before opening the camera.'); return } if (!window.isSecureContext) { cameraError('Camera requires HTTPS. Open this page from an HTTPS web app.'); return } if (!navigator.mediaDevices?.getUserMedia) { cameraError('Camera is not supported on this device/browser. Photo upload is disabled.'); return } await openCamera() }
async function openPreviousCamera(t) { cameraTarget = t; if (!window.isSecureContext) { cameraError('Camera requires HTTPS. Open this page from an HTTPS web app.'); return } if (!navigator.mediaDevices?.getUserMedia) { cameraError('Camera is not supported on this device/browser. Photo upload is disabled.'); return } await openCamera() }
async function openCamera() { try { cameraStream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: 'environment' }, width: { ideal: 1280 }, height: { ideal: 720 } }, audio: false }); $('cameraVideo').srcObject = cameraStream; $('modalCameraErr').textContent = ''; $('cameraModal').classList.add('open') } catch (e) { cameraError(e.name === 'NotAllowedError' ? 'Camera permission denied. Enable camera permission for this website.' : e.name === 'NotFoundError' ? 'No camera is available on this device.' : 'Camera could not be opened. Check browser camera permission.') } }
function cameraError(m) { $('modalCameraErr').textContent = m; if (cameraTarget === 'checkin') { $('cameraErr').textContent = m; $('cameraText').textContent = '✕ ' + m; $('cameraText').className = 'statusline status bad' } else if (cameraTarget === 'checkout') { $('outCameraErr').textContent = m; $('outCameraText').textContent = '✕ ' + m; $('outCameraText').className = 'statusline status bad' } else $(cameraTarget === 'pin' ? 'pinErr' : 'poutErr').textContent = m }
function closeCamera() { if (cameraStream) { cameraStream.getTracks().forEach(t => t.stop()); cameraStream = null } $('cameraModal').classList.remove('open') }
function capturePhoto() { if (!cameraStream) return; const c = document.createElement('canvas'), v = $('cameraVideo'); c.width = v.videoWidth || 1280; c.height = v.videoHeight || 720; c.getContext('2d').drawImage(v, 0, 0, c.width, c.height); const raw = c.toDataURL('image/jpeg', .86); closeCamera(); stamp(raw).then(data => { if (cameraTarget === 'checkin') { photo = data; $('checkinPreview').innerHTML = '<img src="' + data + '">'; $('checkinPreview').classList.remove('hidden'); $('cameraText').innerHTML = svgCheck() + ' Camera photo captured with timestamp + GPS'; $('cameraErr').textContent = ''; $('checkinBtn').disabled = false } else if (cameraTarget === 'checkout') { outPhoto = data; $('checkoutPreview').innerHTML = '<img src="' + data + '">'; $('checkoutPreview').classList.remove('hidden'); $('outCameraText').innerHTML = svgCheck() + ' Camera photo captured with timestamp + GPS'; $('outCameraErr').textContent = ''; $('checkoutBtn').disabled = false } else { previousPhotos[cameraTarget] = data; $(cameraTarget === 'pin' ? 'pinMeta' : 'poutMeta').textContent = '✓ Camera photo captured' } }).catch(() => cameraError('Photo could not be processed.')) }
function stamp(raw) { return new Promise((resolve, reject) => { const img = new Image(); img.onload = () => { const max = 1600, scale = Math.min(1, max / Math.max(img.width, img.height)), c = document.createElement('canvas'); c.width = Math.round(img.width * scale); c.height = Math.round(img.height * scale); const x = c.getContext('2d'); x.drawImage(img, 0, 0, c.width, c.height); const h = Math.max(82, Math.round(c.height * .10)); x.fillStyle = 'rgba(0,0,0,.78)'; x.fillRect(0, c.height - h, c.width, h); x.fillStyle = '#fff'; x.font = '700 ' + Math.max(14, Math.round(c.width / 55)) + 'px Arial'; x.fillText(new Date().toLocaleString(), 14, c.height - h + 28); const g = cameraTarget === 'checkin' ? geo : cameraTarget === 'checkout' ? outGeo : null; if (g) { x.font = Math.max(12, Math.round(c.width / 72)) + 'px Arial'; x.fillText('GPS: ' + g.latitude.toFixed(6) + ', ' + g.longitude.toFixed(6) + ' | ±' + Math.round(g.accuracy) + 'm', 14, c.height - h + 58) } resolve(c.toDataURL('image/jpeg', .78)) }; img.onerror = reject; img.src = raw }) }
async function checkInNow() { if (!validDetails() || !geo || !photo) return; $('checkinBtn').disabled = true; recordId = recordId || ((crypto.randomUUID && crypto.randomUUID()) || Date.now() + '-' + Math.random()); $('checkinErr').textContent = ''; try { await send('checkIn', { ...details(), recordId, photoData: photo, latitude: geo.latitude, longitude: geo.longitude, accuracy: geo.accuracy }); checkInTime = new Date().toISOString(); saveActive(); scheduleExpiry(); show('checkout'); getCheckoutLocation(); toast('Check-in recorded. Check-out is available for 3 hours.') } catch (e) { $('checkinErr').textContent = 'Check-in could not be submitted. Please try again.'; $('checkinBtn').disabled = false } }
function restoreActive(a) { mode = a.mode || 'LIVE'; recordId = a.recordId; geo = a.geo; photo = a.photo; outGeo = a.outGeo; outPhoto = a.outPhoto; checkInTime = a.checkInTime || null; scheduleExpiry(); const f = a.form || {}; Object.keys(f).forEach(k => { if ($(k)) $(k).value = f[k] }); setDateMode(); $('close').disabled = !$('open').value; if (mode === 'LIVE') { show('checkout'); if (outGeo) { $('outLocIcon').classList.add('ok'); $('outLocText').innerHTML = svgCheck() + ' Location successfully fetched'; $('outLocMeta').textContent = 'Latitude ' + outGeo.latitude.toFixed(6) + ' · Longitude ' + outGeo.longitude.toFixed(6) + ' · Accuracy ±' + Math.round(outGeo.accuracy) + ' m'; $('outCameraBtn').disabled = false } if (outPhoto) { $('checkoutPreview').innerHTML = '<img src="' + outPhoto + '">'; $('checkoutPreview').classList.remove('hidden'); $('outCameraText').innerHTML = svgCheck() + ' Camera photo restored after refresh'; $('checkoutBtn').disabled = false } } }
async function checkoutNow() { if (checkInTime && Date.now() - new Date(checkInTime).getTime() >= SESSION_LIMIT_MS) { expireActiveSession(); return } if (!outGeo || !outPhoto) return; $('checkoutBtn').disabled = true; $('checkoutErr').textContent = ''; try { const started = loadActive(); await send('checkOut', { recordId, photoData: outPhoto, latitude: outGeo.latitude, longitude: outGeo.longitude, accuracy: outGeo.accuracy }); const ci = started?.checkInTime ? new Date(started.checkInTime) : new Date(); const co = new Date(); const dm = Math.max(0, Math.floor((co - ci) / 60000)), dur = String(Math.floor(dm / 60)).padStart(2, '0') + ':' + String(dm % 60).padStart(2, '0'); clearSession(); $('feedbackSummary').innerHTML = '<div class="summaryrow"><strong>Supervisor</strong><span>' + esc($('visitor').value) + '</span></div><div class="summaryrow"><strong>School</strong><span>' + esc($('school').value) + '</span></div><div class="summaryrow"><strong>Visit date</strong><span>' + esc($('date').value) + '</span></div><div class="summaryrow"><strong>Check-in / session start</strong><span>' + ci.toLocaleString() + '</span></div><div class="summaryrow"><strong>Check-out</strong><span>' + co.toLocaleString() + '</span></div><div class="summaryrow"><strong>Duration</strong><span><b>' + dur + '</b></span></div><div class="summaryrow"><strong>Status</strong><span class="status ok">Completed</span></div>'; show('feedback') } catch (e) { $('checkoutErr').textContent = 'Check-out could not be submitted. The active session remains saved. Please try again.'; $('checkoutBtn').disabled = false } }
async function savePrevious() { const ci = $('pci').value, co = $('pco').value; let ok = true; $('pciErr').textContent = ci ? '' : 'Check-in is required.'; $('pcoErr').textContent = co ? '' : 'Check-out is required.'; if (ci && co && co <= ci) $('pcoErr').textContent = 'Check-out must be later than check-in.'; $('pinErr').textContent = previousPhotos.pin ? '' : 'Camera photo required.'; $('poutErr').textContent = previousPhotos.pout ? '' : 'Camera photo required.'; document.querySelectorAll('#previous .error').forEach(e => { if (e.textContent) ok = false }); if (!ok) return; $('prevSave').disabled = true; recordId = (crypto.randomUUID && crypto.randomUUID()) || Date.now() + '-' + Math.random(); try { await send('previousVisit', { ...details(), recordId, checkInDateTime: ci, checkOutDateTime: co, checkInPhotoData: previousPhotos.pin, checkOutPhotoData: previousPhotos.pout }); $('feedbackSummary').innerHTML = '<div class="summaryrow"><strong>Supervisor</strong><span>' + esc($('visitor').value) + '</span></div><div class="summaryrow"><strong>School</strong><span>' + esc($('school').value) + '</span></div><div class="summaryrow"><strong>Status</strong><span class="status ok">Previous supervision saved</span></div>'; clearSession(); show('feedback') } catch (e) { toast('Previous supervision could not be submitted. Please try again.') } finally { $('prevSave').disabled = false } }
function esc(s) { return String(s || '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[c])) }
init();
